import { extractRecord, type ExtractFailure } from "$lib/server/pdfcx";

// A record can arrive either wrapped in a PDF or on its own as JSON. The JSON
// route exists so a record written or generated by hand imports without anyone
// having to produce a PDF around it first.
export type SourceFailure = ExtractFailure | "damaged-json" | "not-supported";
export type SourceResult = { ok: true; record: unknown } | { ok: false; reason: SourceFailure };

function looksLikePdf(bytes: Uint8Array): boolean {
  return new TextDecoder("latin1").decode(bytes.subarray(0, 1024)).includes("%PDF-");
}

export async function recordFromUpload(bytes: Uint8Array): Promise<SourceResult> {
  if (looksLikePdf(bytes)) return extractRecord(bytes);

  let text: string;
  try {
    text = new TextDecoder("utf-8", { fatal: false }).decode(bytes).trim();
  } catch (_) {
    return { ok: false, reason: "not-supported" };
  }

  try {
    return { ok: true, record: JSON.parse(text) };
  } catch (_) {
    // Distinguish "you gave us broken JSON" from "you gave us something else
    // entirely", because only the first is worth going back and fixing.
    const looksJson = text.startsWith("{") || text.startsWith("[");
    return { ok: false, reason: looksJson ? "damaged-json" : "not-supported" };
  }
}
